#!/bin/bash
# Fully update the git repo that we are sitting in

git fetch --all && git pull && git submodule init && git submodule update && git submodule foreach git fetch --all && git submodule foreach git checkout master && git submodule foreach git pull
